export enum Estado {
    PENDIENTE = "PENDIENTE",
    FACTURADO = "FACTURADO",
    PREPARACION = "PREPARACION",
    DELIVERY = "DELIVERY",
    ENTREGADO = "ENTREGADO",
    PREPARADO = "PREPARADO",
    CANCELADO = "CANCELADO"
}